services:
  wbgt-r-api:
    build:
      context: ./backend
    container_name: wbgt-r-api
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app_prototype:/app/app_prototype:ro
