services:
  - type: web
    name: wbgt-r-api
    runtime: docker
    plan: free
    region: singapore
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: 10000
