apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wbgt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ptrpspeen/WBGT-App.git
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: test-digitech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
